### ISSUE TITLE
Issue 77 checklist

### ISSUE THREAD

**Issue by laserkelvin** [astropah/newsletter#3]
Files to check:
- [ ] `cover/cover.png`

Updates to `issue_details.md`:

- [ ] Next issue deadlines updated
- [ ] Issue number incremented
- [ ] POTM
- [x] POTM caption
- [ ] POTM credits

Section checklist:

- [x] Announcements
- [ ] Interview
- [ ] InFocus
- [ ] Meetings
- [ ] Abstracts
